# Word-level training data - focused on complete words and sentences
WORD_CONVERSATIONS = [
    "Mholo|Mholo unjani",
    "Unjani|Ndiyaphila enkosi", 
    "Ndiyaphila wena unjani|Ndiyaphila kakhulu",
    "Ungubani igama lakho|Igama lam nguThandi",
    "Uvela phi|Ndivela eKapa",
    "Uhlala phi|Ndihlala eGoli",
    "Uyasebenza|Ewe ndiyasebenza",
    "Ufunda phi|Ndiafunda kwalapha eKapa",
    "Usapho lwakho lunjani|Usapho lwam luyaphila",
    "Enkosi|Wamkelekile",
    "Shiyeka kakuhle|Hamba kakuhle",
    "Uthanda ntoni|Ndithanda ukufunda",
    "Kulungile|Ewe kulungile",
    "Uyasithanda isikolo|Ewe ndiyasithanda",
    "Uyasithetha isiNgesi|Ewe ndiyasithetha",
    "Uyaphi|Ndiya edolophini",
    "Uyothenga ntoni|Ndizothenga ukutya",
    "Ixesha ngubani|Ixesha ngu-3",
    "Kushushu namhlanje|Ewe kushushu kakhulu",
    "Kuyabanda|Hayi akubandi",
    "Uyathanda imvula|Ewe ndiyayithanda",
    "Uyayisela itiye|Ewe ndiyayisela",
    "Uyayidlala ibhola|Hayi andiyidlali",
    "Uneminyaka emingaki|Ndineminyaka eyi-25",
    "Uzalwe nini|Ndazalwa ngoMeyi 15",
    "Usapho lwakho lukhulu|Ewe lukhulu kakhulu",
    "Unabazali|Ewe ndinabo bobabini",
    "Unabantwana|Ewe ndinabantwana ababini",
    "Abantwana bakho banangaphi|Omnye una-1 omnye una-2",
    "Bafunda phi|Bafunda esikolweni",
    "Babhadlile|Ewe babhadle kakhulu",
    "Uyabathanda|Ewe ndiyabathanda kakhulu",
    "Uyamxhela umntwana|Hayi andimxheli",
    "Uyamnika isipho|Ewe ndiyamnika",
    "Umfundisa ntoni|Ndimfundisa ukufunda",
    "Uyamkhulisa kakuhle|Ewe ndiyamkhulisa",
    "Uyayithanda imoto yakho|Ewe ndiyayithanda",
    "Wayithenga phi|Ndayithenga edolophini",
    "Iyaxabisa lonto|Ewe iyaxabisa",
    "Unxibe iimpahla ezinjani|Ndinxiba iimpahla ezintle",
    "Uzithengela phi|Ndizithengela edolophini",
    "Ziyabiza kakhulu|Ewe ziyabiza",
    "Uyazithanda iimpahla zakho|Ewe ndiyazithanda",
    "Uzinxiba phi|Ndizinxiba ekhaya",
    "Uyazihlamba|Ewe ndizihlamba",
    "Uyazithengisa|Hayi andizithengisi",
    "Uyazitshintsha|Ewe ndiyazitshintsha",
    "Ubhala phi|Ndibhala ekhaya",
    "Uyaunda|Ewe ndiyafunda",
    "Uyathetha|Ewe ndiyaithetha",
    "Uyazibona|Ewe ndiyazibona",
    "Uyaziva|Ewe ndiyaziva",
    "Uyacinga|Ewe ndizicabangandiyacinga",
    "Uyazifuna|Ewe ndiyazifuna",
    "Uyazithanda|Ewe ndiyazithanda",
    "Uyazikhonza|Hayi andizikhonzi",
    "Uyazibulala|Hayi andizibulali",
    "Uyazisinda|Ewe ndiyazisinda",
    "Uyaziphilisa|Ewe ndyaziphilisa",
    "Uyaziqeqesha|Ewe ndiyaziqeqesha",
    "Uyazifundisa|Ewe ndiyazifundisa",
    "Uyazikhulula|Ewe ndiyazikhulula",
    "Uyazivula|Ewe ndiyazivula",
    "Uyazivala|Ewe ndiyazivala",
    "Uyazibopha|Hayi andizibophi",
    "Uyazikhulula|Ewe ndizikhulula",
    "Uyazibulala|Hayi andizibulali",
    "Uyazisika|Hayi andizisiki",
    "Uyazibopa|Hayi andizibopi",
    "Uyazivula|Ewe ndiyazivula",
    "Uyazivala|Ewe ndiyazivala",
    "Uyazibona|Ewe ndizibona",
    "Uyazibamba|Ewe ndiyazibamba",
    "Uyazikhulula|Ewe ndiyazikhulula",
    "Uyazibulala|Hayi andizibulali",
    "Uyazisika|Hayi andizisiki",
    "Uyazibopa|Hayi andizibopi",
    "Uyazivula|Ewe ndiyazivula",
    "Uyazivala|Ewe ndiyazivala",
    "Uyazibona|Ewe ndiyazibona",
    "Uyazibamba|Ewe ndiyazibamba",
    "Uyazikhulula|Ewe ndiyazikhulula",
    "Uyazibulala|Hayi andizibulali",
    "Uyazisika|Hayi andizisiki",
    "Uyazibopa|Hayi andizibopi",
    "Uyazivula|Ewe ndiyazivula",
    "Uyazivala|Ewe ndiyazivala",
    "Uyazibona|Ewe ndiyazibona",
    "Uyazibamba|Ewe ndiyazibamba",
    "Uyazikhulula|Ewe ndiyazikhulula",
    "Uyazibulala|Hayi andizibulali",
    "Uyazisika|Hayi andizisiki",
    "Uyazibopa|Hayi andizibopi",
    "Uyazivula|Ewe ndiyazivula",
    "Uyazivala|Ewe ndiyazivala",
    "Uyazibona|Ewe ndiyazibona",
    "Uyazibamba|Ewe ndiyazibamba",
    "Uyazikhulula|Ewe ndiyazikhulula",
    "Uyazibulala|Hayi andizibulali",
    "Uyazisika|Hayi andizisiki",
    "Uyazibopa|Hayi andizibopi",
    "Uyazivula|Ewe ndiyazivula",
    "Uyazivala|Ewe ndiyazivala",
    "Uyazibona|Ewe ndiyazibona",
    "Uyazibamba|Ewe ndiyazibamba"
]

WORD_VOCABULARY = [
    "umntu", "abantu", "indoda", "intombi", "umfana", "umntwana",
    "umama", "utata", "usapho", "igama", "ilizwe", "ihlathi",
    "isikolo", "indlela", "ithuba", "amandla", "ubuntu", "ukutya",
    "ukusela", "ukulala", "ukuphumla", "ukufunda", "ukubhala", "enkosi",
    "wamkelekile", "kulungile", "kakuhle", "kakhulu", "phantsi", "phezulu",
    "qiniseka", "yiza", "hamba", "jonga", "thetha", "lalela", "cinga",
    "funda", "bhala", "dlala", "sebenza", "phumla", "thanda", "zola",
    "xelela", "bona", "va", "ba", "za", "wa", "ja", "ka", "la", "ma",
    "na", "pa", "qa", "ra", "sa", "ta", "va", "wa", "xa", "ya", "za",
    "aba", "ebe", "ibi", "obo", "ubu", "ada", "ede", "idi", "odo", "udu",
    "afa", "efe", "ifi", "ofo", "ufu", "aga", "ege", "igi", "ogo", "ugu",
    "aka", "eke", "iki", "oko", "uku", "ala", "ele", "ili", "olo", "ulu",
    "ama", "eme", "imi", "omo", "umu", "ana", "ene", "ini", "ono", "unu",
    "apa", "epe", "ipi", "opo", "upu", "aqa", "eqe", "iqi", "oqo", "uqu",
    "ara", "ere", "iri", "oro", "uru", "asa", "ese", "isi", "oso", "usu",
    "ata", "ete", "iti", "oto", "utu", "ava", "eve", "ivi", "ovo", "uvu",
    "awa", "ewe", "iwi", "owo", "uwu", "axa", "exe", "ixi", "oxo", "uxu",
    "aya", "eye", "iyi", "oyo", "uyu", "aza", "eze", "izi", "ozo", "uzu",
    "inda", "ende", "indi", "ondo", "undu", "inga", "enge", "ingi", "ongo",
    "ungu", "inka", "enke", "inki", "onko", "unku", "inxa", "enxe", "inxi",
    "onxo", "unxu", "inca", "ence", "inci", "onco", "uncu", "inga", "enge",
    "ingi", "ongo", "ungu", "inza", "enze", "inzi", "onzo", "unzu"
]

def get_word_corpus():
    """Get corpus for word-level N-gram training"""
    # Combining conversations and vocabulary
    conversation_text = " ".join(" ".join(conv.split("|")) for conv in WORD_CONVERSATIONS)
    vocab_text = " ".join(WORD_VOCABULARY)
    return conversation_text + " " + vocab_text

def get_word_list():
    """Get words as list for training"""
    return get_word_corpus().split()